name: Generate Geodats and Routing Configurations

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run generate_dat.py (geosite.dat & geoip.dat)
        run: python generate_dat.py

      - name: Run generate_routing.py (routing configurations)
        run: python generate_routing.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Automated update: geodats and routing configurations [skip ci]"
          add: "geosite.dat geoip.dat routing_proxy.json routing_adguard.json"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
